### ISSUE TITLE
Peer Review #1

### ISSUE THREAD

**Issue by MariaMangru** [kevicai/toronto-healthcare-outbreak-prediction#1]
### Summary:
The project "Toronto Healthcare Outbreak Prediction" aims to analyze and predict the duration of outbreaks in Toronto healthcare institutions. The fundamental elements such as data processing and model fitting are present. Some components such as literature reviews, complete paper sections, and updated sketches are yet to be developed.

### Strong positive points:

- The repository clearly separates raw data, cleaned data, models, scripts, and other materials into distinct folders, making navigation straightforward.
- Covers all major steps from data simulation (00-simulate_data.py) to modeling (07-model_data.R), providing a solid foundation for the analysis.
- Includes test scripts using pytest to ensure data integrity and script functionality.
- Utilizes appropriate statistical models like Poisson and Negative Binomial regression with the rstanarm package in R, suitable for count data with overdispersion.

### Critical improvements needed:

- While there’s a statement on using tools like Codriver and ChatHorse, the specific contributions and interactions are not well-documented.
- Currently using CSV files, which can be inefficient for large datasets. Switching to formats like Parquet would improve performance.
- Important sections like literature review, detailed methodology, results, and discussion in the paper are missing or underdeveloped.

### Suggestions for improvement:

- Develop all sections of paper.qmd, including a detailed abstract, introduction, literature review, methodology, results, and discussion.
- Provide clear documentation on how LLM tools were used in the project.
- Update the README with a comprehensive overview, setup instructions, and usage guidelines.
- Convert large CSV files to Parquet for better performance and storage efficiency.
- Add more tests to cover different aspects of data processing and model validation to ensure robustness.
- Incorporate relevant sketches and literature reviews to provide context and support for the analysis.

### Evaluation:

- R is appropriately cited: 1/1 (R and relevant packages are cited in the paper.).
- Data are appropriately cited: 1/1 (Data sources mentioned but not formally cited in the paper.).
- Class paper: 1/1 (Looks professional, not like a class project).
- LLM usage is documented: 0/1 (LLM usage is mentioned but not documented.).
- Title: 1/2 (Title present but subtitle is generic and needs to reflect findings.).
Author, date, and repo: 2/2 (All elements are provided.).
Abstract: 0/4 (No abstract provided).
Introduction: 0/4 (No introduction provided).
Estimand: 0.5/1 (Implicitly defined within the model setup.).
Data: 5/10 (Partially complete but needs more details and efficient handling.).
Measurement: 4/4 (Well-detailed and clearly explains variables.).
Model: 6/10 (Outlined with appropriate techniques but needs full validation.).
Results: 2/10 (Minimal and requires substantial development.).
Discussion: 0/10 (No discussion provided).
Prose: 2/6 (Moderate quality; needs refinement for clarity.).
Cross-references: 0/1 (Cross-references are not provided).
Captions: 1/2 (Some captions provided but lack detail.).
Graphs/tables/etc: 2/4 (Included but need better integration and explanation.).
Idealized methodology: 3/10 (Partially described; needs comprehensive coverage.).
Idealized survey: 0/4 (The survey discussion is not provided).
Pollster methodology overview and evaluation: 0/10 (Basic overview present but lacks depth.).
Referencing: 0/4 (References included but need proper formatting.).
Commits: 2/2 (Well done).
Sketches: 0/2 (Sketches are not updated).
Simulation: 4/4 (Well done.).
Tests – simulation: 2/4 (Some tests included but need to be more comprehensive.).
Tests – actual: 2/4 (Basic tests present; additional coverage needed.).
Parquet: 0/1 (Data is in .csv, not .parquet).
Reproducible workflow: 4/4 (Well done.).
Miscellaneous: 0/3 (No additional notes).

Estimated overall mark:
40.5/126

Since the paper does not include complete LLM usage documentation, then the paper gets 0 overall.

**Comment by kevicai** [comment]
Fixed. Thanks for the feedback!
