### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by XYPKQ896** [kevicai/toronto-healthcare-outbreak-prediction#2]
Summary
Complete simulation, data downloading and cleaning, model. Paper has not completed yet.
Strong positive points:
Models looks well. Readme updates the title instead of start file.
Critical improvements needed:
It is better to delete the folders you do not need. 
Also, I want to see the sketches of the project.
Suggestions for improvement:
Write a subtitle for the title of your paper.
Abstracts are needed to attract readers' views.
Evaluation:
Make sure to complete the parts needed and delete the ciatation you do not use.
R/Python cited ([0]/1 pts)
No
Data cited ([1]/1 pts)
Good
Class paper ([1]/1 pts)
Not class paper.
LLM documentation ([0]/1 pts)
[Not update yet]
Title ([1]/2 pts)
[Need subtitle]
Author, date, and repo ([2]/2 pts)
[Good]
Abstract ([0]/4 pts)
[No abstract]
Introduction ([0]/4 pts)
[No introduction]
Estimand ([0]/1 pts)
[Not exists]
Data ([0]/10 pts)
[No data]
Measurement ([4]/4 pts)
[Good]
Model ([10]/10 pts)
[Good]
Results ([5]/10 pts)
[Need interpretation]
Discussion ([0]/10 pts)
[Not exists]
Prose ([0]/6 pts)
[Not exists]
Cross-references ([1]/1 pts)
[exists]
Captions ([0]/2 pts)
[Not exists]
Graphs/tables/etc ([4]/4 pts)
[Good]
Surveys, sampling, and observational data appendix ([5]/10 pts)
[Not exists]
Referencing ([2]/4 pts)
[Not include R]
Commits ([2]/2 pts)
[Good]
Sketches ([0]/2 pts)
[Not exists]
Simulation ([4]/4 pts)
[Good]
Tests ([4]/4 pts)
[Good]
Parquet ([0]/1 pts)
[No dataset]
Reproducible workflow ([4]/4 pts)
[Good]
Enhancements ([0]/4 pts)
[Not exists]
Miscellaneous ([0]/3 pts)
[Not exists]
Estimated overall mark:
[45] out of [112].
Any other comments:
Remember to push your data to github.

**Comment by kevicai** [comment]
Fixed. Thanks for the feedback!
